# Form implementation generated from reading ui file 'practicaExe.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(233, 314)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/imagenes/Animals.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 230, 141, 61))
        self.pushButton.setStyleSheet("border-radius:5px;\n"
"background-color: rgb(170, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/imagenes/exit-60.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(60, 60))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(30, 190, 113, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"color: rgb(5, 5, 5);")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 140, 91, 41))
        self.label.setStyleSheet("background-color: rgb(255, 0, 127);\n"
"color: rgb(255, 255, 0);")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 161, 111))
        self.label_2.setStyleSheet("alternate-background-color: rgb(255, 170, 0);\n"
"background-color: rgb(0, 170, 255);")
        self.label_2.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/imagenes/facebook-480.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        self.pushButton.clicked.connect(Form.close)
        self.lineEdit.textChanged['QString'].connect(self.label.setText)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Ejemplo"))
        self.pushButton.setText(_translate("Form", "Botón"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Entrada"))
        self.label.setText(_translate("Form", "Etiqueta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
